# Imagine this Situation

Tumhare school me ek question poocha gaya:

"Kal baarish hogi ya nahi?"

Ek hi student se puchoge to ho sakta hai wo galat bole.

Lekin agar 100 students se pucho aur:

70 bole "Hogi"

30 bole "Nahi hogi"

To tum kis par trust karoge?

👉 70 wali majority par.

Yahi idea Bagging ka hai.

# Machine Learning me kya hota hai?

Maan lo tumhare paas 1 teacher (model) hai.

Wo prediction karta hai.

Kabhi sahi.

Kabhi galat.

Ab socho tum 10 alag teachers bana do.

Har teacher thoda alag data dekhkar seekhe.

Ab prediction karte waqt sabse opinion lo.

Fir majority vote lo.

Final answer jyada accurate hoga.

Yahi Bagging hai.

#Why Bagging?

Ek model galti kar sakta hai.

Lekin bahut saare models agar independent hain,

to sab ek hi jagah galti nahi karenge.

Isliye final prediction better hota hai.

# Why Bagging

Bootstrap Aggregating

# Bootstrap

Matlab

Original data se random samples banana (replacement ke saath).

Example:

Original Data

A B C D E

Ek bootstrap sample ho sakta hai

A B B D E

Ya

C D A A E

Notice:

Same row dobara aa sakti hai.

Kuch rows miss bhi ho sakti hain.

# Aggregating

Sab models ka result combine karna.

Jaise

Tree1

Tree2

Tree3

Tree4

Sabki prediction collect ki.

Final vote liya.

Bas.

# Bagging ek technique hai jisme ek hi dataset se kai random datasets banaye jaate hain, har dataset par alag model train hota hai, aur sab models ki prediction ko combine karke final prediction diya jaata hai. Isse prediction zyada stable aur accurate ho jaati hai.

# Main Goal

✅ Ek model par depend na rehna

✅ Galti kam karna

✅ Prediction ko stable banana

✅ Overfitting kam karna (especially Decision Trees me)

```
| Model                         | Bias  | Variance | Reason                                                                                                             |
| ----------------------------- | ----- | -------- | ------------------------------------------------------------------------------------------------------------------ |
| Decision Tree                 | ✅ Low | ❌ High   | Data ko bahut closely fit karta hai, isliye data badalte hi tree badal jata hai.                                   |
| Bagging (many Decision Trees) | ✅ Low | ✅ Lower  | Bahut saare trees ki prediction combine hoti hai, isliye individual trees ki instability average out ho jaati hai. |
```

# "Bagging ka main purpose variance ko reduce karna hai. Isme multiple models ko alag-alag bootstrap samples par train kiya jata hai aur unki predictions ko average ya majority voting se combine kiya jata hai. Kyunki ek model ki galti dusre models balance kar dete hain, final prediction zyada stable hoti hai. Isliye Bagging variance ko kam karta hai, jabki bias me bahut kam ya lagbhag koi change nahi hota."

# Code

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
df.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:

from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()

In [ ]:

df.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
df.head()

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df_train = df.iloc[:60,:].sample(10)
df_train

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
14,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0
16,33.60,28.0,1678.0,322.0,666.0,256.0,2.9653,94900.0
48,32.99,20.0,1402.0,287.0,1104.0,317.0,1.9088,63700.0
41,32.67,29.0,1523.0,440.0,1302.0,393.0,1.1311,84700.0
26,32.82,30.0,1602.0,322.0,1130.0,335.0,3.5735,71100.0
58,32.67,6.0,2804.0,581.0,2807.0,594.0,2.0625,67700.0
55,32.97,10.0,1879.0,387.0,1376.0,337.0,1.9911,67500.0
53,32.98,32.0,1615.0,382.0,1307.0,345.0,1.4583,58600.0
45,32.67,35.0,2159.0,492.0,1694.0,475.0,2.1776,75500.0
12,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0

In [ ]:
# Taking only 10 rows for training
df = df.sample(100)
df_train = df.iloc[:60,:].sample(10)
df_val = df.iloc[60:80,:].sample(5)
df_test = df.iloc[80:,:].sample(5)

In [ ]:
df_train

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0
6432,34.68,19.0,552.0,129.0,314.0,106.0,3.2125,185400.0
5313,33.76,52.0,2677.0,642.0,1144.0,624.0,4.3889,378000.0
785,32.60,25.0,1075.0,238.0,434.0,234.0,1.7472,94600.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
5216,33.78,31.0,3039.0,739.0,1199.0,697.0,3.7232,500001.0
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
12012,38.57,25.0,2022.0,295.0,639.0,278.0,5.8416,297600.0

In [ ]:
df_val

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
6148,33.91,33.0,677.0,182.0,984.0,174.0,2.5893,88900.0
16699,38.38,27.0,2565.0,479.0,1227.0,467.0,4.5132,259900.0
8424,34.00,37.0,2586.0,765.0,1801.0,737.0,2.6042,305800.0
13458,37.33,31.0,1866.0,465.0,821.0,447.0,2.3547,275900.0
7724,34.05,52.0,1241.0,210.0,526.0,214.0,4.4191,334100.0

In [ ]:
df_test

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8078,33.97,44.0,1462.0,240.0,562.0,237.0,4.9375,365200.0
12615,39.41,22.0,1814.0,342.0,941.0,323.0,2.1728,59400.0
3231,34.13,29.0,630.0,145.0,378.0,148.0,3.4107,170800.0
375,32.76,9.0,1859.0,307.0,947.0,304.0,5.9202,181300.0
8133,34.16,34.0,2622.0,467.0,1233.0,476.0,4.0474,379700.0

In [ ]:
X_test = df_val.iloc[:,0:2].values
y_test = df_val.iloc[:,-1].values

In [ ]:
y_test

array([ 88900., 259900., 305800., 275900., 334100.])

# Case1. Bagging

In [ ]:
# Data for Tree 1
df_bag = df_train.sample(8,replace=True)

X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

df_bag

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
12012,38.57,25.0,2022.0,295.0,639.0,278.0,5.8416,297600.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0
5313,33.76,52.0,2677.0,642.0,1144.0,624.0,4.3889,378000.0
12012,38.57,25.0,2022.0,295.0,639.0,278.0,5.8416,297600.0

In [ ]:

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from mlxtend.plotting import plot_decision_regions
from sklearn.metrics import accuracy_score

In [ ]:
dt_bag1 = DecisionTreeClassifier()

In [ ]:
# Define the evaluate function
# This function should ideally be defined in an earlier cell (e.g., with other imports),
# but for demonstration purposes to fix the NameError in this specific cell, it is defined here.
def evaluate(model, X_train, y_train, X_test_data, y_test_data):
    """
    Evaluates a given model on training and test data.
    Prints a warning if a classifier is used with continuous target variables.
    """
    model.fit(X_train, y_train)
    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test_data)

    print(f"Model: {model.__class__.__name__}")
    print(f"Training Data Shape: {X_train.shape}, Target Shape: {y_train.shape}")
    print(f"Test Data Shape: {X_test_data.shape}, Target Shape: {y_test_data.shape}")

    # Check if the target is continuous or categorical (simple heuristic)
    if np.issubdtype(y_train.dtype, np.number) and len(np.unique(y_train)) > 10:
        print("\nWarning: The target variable appears to be continuous (e.g., 'median_house_value').")
        print("Using a DecisionTreeClassifier for a continuous target is generally incorrect.")
        print("For regression tasks, consider using DecisionTreeRegressor and appropriate regression metrics (e.g., R2 score, Mean Squared Error).")
        from sklearn.metrics import r2_score, mean_squared_error
        try:
            r2_train = r2_score(y_train, y_pred_train)
            mse_train = mean_squared_error(y_train, y_pred_train)
            r2_test = r2_score(y_test_data, y_pred_test)
            mse_test = mean_squared_error(y_test_data, y_pred_test)
            print(f"Training R2 Score: {r2_train:.4f}")
            print(f"Training MSE: {mse_train:.2f}")
            print(f"Test R2 Score: {r2_test:.4f}")
            print(f"Test MSE: {mse_test:.2f}")
        except Exception as e:
            print(f"Could not calculate regression metrics: {e}")
    else: # Assume classification if not clearly continuous
        from sklearn.metrics import accuracy_score
        try:
            train_accuracy = accuracy_score(y_train, y_pred_train)
            test_accuracy = accuracy_score(y_test_data, y_pred_test)
            print(f"Training Accuracy: {train_accuracy:.4f}")
            print(f"Test Accuracy: {test_accuracy:.4f}")
        except ValueError as e:
            print(f"Error calculating accuracy_score: {e}")
            print("This usually happens if target labels are not compatible (e.g., continuous values for classification metric).")

# Now call the function with the model, training data, and test data
evaluate(dt_bag1,X,y,X_test,y_test)

Model: DecisionTreeClassifier
Training Data Shape: (8, 2), Target Shape: (8,)
Test Data Shape: (5, 2), Target Shape: (5,)
Training Accuracy: 1.0000
Test Accuracy: 0.0000

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:

# Data for Tree 1
df_bag = df_train.sample(8,replace=True)

# Fetch X and y
X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

# print df_bag
df_bag

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5216,33.78,31.0,3039.0,739.0,1199.0,697.0,3.7232,500001.0
12012,38.57,25.0,2022.0,295.0,639.0,278.0,5.8416,297600.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
6432,34.68,19.0,552.0,129.0,314.0,106.0,3.2125,185400.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0

In [ ]:
dt_bag2 = DecisionTreeClassifier()
evaluate(dt_bag2,X,y,X_test,y_test)

Model: DecisionTreeClassifier
Training Data Shape: (8, 2), Target Shape: (8,)
Test Data Shape: (5, 2), Target Shape: (5,)
Training Accuracy: 1.0000
Test Accuracy: 0.0000

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
# Data for Tree 1
df_bag = df_train.sample(8,replace=True)

# Fetch X and y
X = df_bag.iloc[:,0:2]
y = df_bag.iloc[:,-1]

# print df_bag
df_bag

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
785,32.60,25.0,1075.0,238.0,434.0,234.0,1.7472,94600.0
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
6432,34.68,19.0,552.0,129.0,314.0,106.0,3.2125,185400.0
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0
785,32.60,25.0,1075.0,238.0,434.0,234.0,1.7472,94600.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0

In [ ]:
dt_bag3 = DecisionTreeClassifier()
evaluate(dt_bag3,X,y,X_test,y_test)

Model: DecisionTreeClassifier
Training Data Shape: (8, 2), Target Shape: (8,)
Test Data Shape: (5, 2), Target Shape: (5,)
Training Accuracy: 1.0000
Test Accuracy: 0.0000

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
def evaluate(clf,X,y):
    clf.fit(X,y)
    plot_tree(clf)
    plt.show()
    plot_decision_regions(X.values, y.values, clf=clf, legend=2)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test,y_pred))

# Predict

In [ ]:

df_test

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8078,33.97,44.0,1462.0,240.0,562.0,237.0,4.9375,365200.0
12615,39.41,22.0,1814.0,342.0,941.0,323.0,2.1728,59400.0
3231,34.13,29.0,630.0,145.0,378.0,148.0,3.4107,170800.0
375,32.76,9.0,1859.0,307.0,947.0,304.0,5.9202,181300.0
8133,34.16,34.0,2622.0,467.0,1233.0,476.0,4.0474,379700.0

In [ ]:
print("Predictor 1",dt_bag1.predict(np.array([2.2,5.0]).reshape(1,2)))
print("Predictor 2",dt_bag2.predict(np.array([2.2,5.0]).reshape(1,2)))
print("Predictor 3",dt_bag3.predict(np.array([2.2,5.0]).reshape(1,2)))

Predictor 1 [213200.]
Predictor 2 [254000.]
Predictor 3 [213200.]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

# Pasting

In [ ]:
# Row sampling without replacement
df_train

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0
6432,34.68,19.0,552.0,129.0,314.0,106.0,3.2125,185400.0
5313,33.76,52.0,2677.0,642.0,1144.0,624.0,4.3889,378000.0
785,32.60,25.0,1075.0,238.0,434.0,234.0,1.7472,94600.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
5216,33.78,31.0,3039.0,739.0,1199.0,697.0,3.7232,500001.0
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
12012,38.57,25.0,2022.0,295.0,639.0,278.0,5.8416,297600.0

In [ ]:
df_train.sample(8)

,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
5313,33.76,52.0,2677.0,642.0,1144.0,624.0,4.3889,378000.0
7298,34.01,35.0,1359.0,359.0,655.0,341.0,2.5568,312500.0
6432,34.68,19.0,552.0,129.0,314.0,106.0,3.2125,185400.0
3245,33.87,12.0,1600.0,251.0,685.0,256.0,5.1784,254000.0
8620,34.21,18.0,3124.0,796.0,1855.0,725.0,2.9389,213200.0
13586,36.97,24.0,3665.0,870.0,1954.0,833.0,2.8036,228500.0
8080,33.96,24.0,4393.0,966.0,1257.0,579.0,5.0714,356100.0
5216,33.78,31.0,3039.0,739.0,1199.0,697.0,3.7232,500001.0

# Random Subspaces

In [ ]:
df1 = pd.read_csv('/content/sample_data/california_housing_train.csv')
df1 = df1.sample(10)

In [ ]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8708,-118.57,34.20,18.0,7157.0,1869.0,4642.0,1699.0,3.1818,208000.0
7703,-118.38,34.17,33.0,1588.0,454.0,739.0,392.0,2.8208,238500.0
7171,-118.33,34.19,46.0,2115.0,463.0,1133.0,439.0,3.7344,222000.0
3541,-117.90,33.65,28.0,2043.0,430.0,1108.0,452.0,5.2549,261800.0
277,-116.68,33.71,21.0,3460.0,711.0,658.0,255.0,3.5882,161100.0
11219,-121.06,38.51,6.0,6873.0,959.0,2354.0,931.0,6.8869,263100.0
10717,-120.62,36.99,32.0,2455.0,508.0,1344.0,492.0,1.9732,69400.0
8655,-118.55,34.41,8.0,21086.0,3945.0,9936.0,3790.0,5.8602,265100.0
2710,-117.69,35.65,5.0,1131.0,276.0,520.0,232.0,4.0167,87500.0
9584,-119.35,36.16,21.0,2751.0,602.0,1496.0,489.0,2.3882,49200.0

In [ ]:
df1.sample(2,replace=True,axis=1)

       housing_median_age  housing_median_age
8708                 18.0                18.0
7703                 33.0                33.0
7171                 46.0                46.0
3541                 28.0                28.0
277                  21.0                21.0
11219                 6.0                 6.0
10717                32.0                32.0
8655                  8.0                 8.0
2710                  5.0                 5.0
9584                 21.0                21.0

# Random Patches

In [ ]:
df1

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
8708,-118.57,34.20,18.0,7157.0,1869.0,4642.0,1699.0,3.1818,208000.0
7703,-118.38,34.17,33.0,1588.0,454.0,739.0,392.0,2.8208,238500.0
7171,-118.33,34.19,46.0,2115.0,463.0,1133.0,439.0,3.7344,222000.0
3541,-117.90,33.65,28.0,2043.0,430.0,1108.0,452.0,5.2549,261800.0
277,-116.68,33.71,21.0,3460.0,711.0,658.0,255.0,3.5882,161100.0
11219,-121.06,38.51,6.0,6873.0,959.0,2354.0,931.0,6.8869,263100.0
10717,-120.62,36.99,32.0,2455.0,508.0,1344.0,492.0,1.9732,69400.0
8655,-118.55,34.41,8.0,21086.0,3945.0,9936.0,3790.0,5.8602,265100.0
2710,-117.69,35.65,5.0,1131.0,276.0,520.0,232.0,4.0167,87500.0
9584,-119.35,36.16,21.0,2751.0,602.0,1496.0,489.0,2.3882,49200.0

In [ ]:

df1.sample(8,replace=True).sample(2,replace=True,axis=1)

       median_income  total_rooms
277           3.5882       3460.0
11219         6.8869       6873.0
10717         1.9732       2455.0
3541          5.2549       2043.0
7171          3.7344       2115.0
8708          3.1818       7157.0
7171          3.7344       2115.0
10717         1.9732       2455.0

# "Bagging ek technique hai jisme ek hi kaam ke liye bahut saare models se alag-alag opinion liya jata hai aur un sabki majority vote ya average ke basis par final decision liya jata hai. Isse kisi ek model ki galti ka chances kam ho jata hai aur prediction zyada stable aur accurate ho jati hai."

# Bagging Classifiers

In [ ]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [ ]:
X,y = make_classification(n_samples=10000, n_features=10,n_informative=3)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

print("Decision Tree accuracy",accuracy_score(y_test,y_pred))

Decision Tree accuracy 0.9365

# Bagging

In [ ]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.5,
    bootstrap=True,
    random_state=42
)

In [ ]:
bag.fit(X_train,y_train)

In [ ]:
y_pred = bag.predict(X_test)

In [55]:

accuracy_score(y_test,y_pred)

0.9635

In [56]:


bag.estimators_samples_[0].shape

(4000,)

# Bagging using SVM

In [59]:
bag = BaggingClassifier(
    estimator=SVC(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    random_state=42
)

In [58]:
bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Bagging using SVM",accuracy_score(y_test,y_pred))

Bagging using SVM 0.9635

# Pasting

In [61]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=False,
    random_state=42,
    verbose = 1,
    n_jobs=-1
)

In [64]:
bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Pasting classifier",accuracy_score(y_test,y_pred))

[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:   18.3s finished
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.

Pasting classifier 0.9615

[Parallel(n_jobs=2)]: Done   2 out of   2 | elapsed:    0.4s finished

# Random Subspaces

In [66]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=1.0,
    bootstrap=False,
    max_features=0.5,
    bootstrap_features=True,
    random_state=42
)

In [67]:
bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Random Subspaces classifier",accuracy_score(y_test,y_pred))

Random Subspaces classifier 0.958

In [68]:
bag.estimators_samples_[0].shape

(8000,)

In [69]:
bag.estimators_features_[0].shape

(5,)

# Random Patches

In [71]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    max_features=0.5,
    bootstrap_features=True,
    random_state=42
)

In [72]:
bag.fit(X_train,y_train)
y_pred = bag.predict(X_test)
print("Random Patches classifier",accuracy_score(y_test,y_pred))

Random Patches classifier 0.959

# OOB Score

In [74]:
bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=500,
    max_samples=0.25,
    bootstrap=True,
    oob_score=True,
    random_state=42
)

In [75]:

bag.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.25,
                  n_estimators=500, oob_score=True, random_state=42)

In [76]:
bag.oob_score_

0.956375

In [77]:
y_pred = bag.predict(X_test)
print("Accuracy",accuracy_score(y_test,y_pred))

Accuracy 0.963

# Bagging Tips

Bagging generally gives better results than Pasting

Good results come around the 25% to 50% row sampling mark

Random patches and subspaces should be used while dealing with high dimensional data

To find the correct hyperparameter values we can do GridSearchCV/RandomSearchCV

# Applying GridSearchCV

In [78]:
from sklearn.model_selection import GridSearchCV

In [79]:
parameters = {
    'n_estimators': [50,100,500],
    'max_samples': [0.1,0.4,0.7,1.0],
    'bootstrap' : [True,False],
    'max_features' : [0.1,0.4,0.7,1.0]
    }

In [80]:

search = GridSearchCV(BaggingClassifier(), parameters, cv=5)

In [ ]:


search.fit(X_train,y_train)

In [ ]:

search.best_params_
search.best_score_

In [ ]:

search.best_params_

# Baggine Regression

In [ ]:
from sklearn import datasets

boston = datasets.load_boston()
X_boston, Y_boston = boston.data, boston.target
print('Dataset features names : '+ str(boston.feature_names))
print('Dataset features size : '+ str(boston.data.shape))
print('Dataset target size : '+ str(boston.target.shape))

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_boston, Y_boston , train_size=0.80, test_size=0.20, random_state=123)
print('Train/Test Sets Sizes : ',X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

In [ ]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
knn = KNeighborsRegressor()

In [ ]:
lr.fit(X_train,Y_train)
dt.fit(X_train,Y_train)
knn.fit(X_train,Y_train)

In [ ]:
y_pred1 = lr.predict(X_test)
y_pred2 = dt.predict(X_test)
y_pred3 = knn.predict(X_test)

In [ ]:
print("R^2 score for LR",r2_score(Y_test,y_pred1))
print("R^2 score for DT",r2_score(Y_test,y_pred2))
print("R^2 score for KNN",r2_score(Y_test,y_pred3))

In [ ]:
from sklearn.ensemble import BaggingRegressor

bag_regressor = BaggingRegressor(random_state=1)
bag_regressor.fit(X_train, Y_train)

In [ ]:
Y_preds = bag_regressor.predict(X_test)

print('Training Coefficient of R^2 : %.3f'%bag_regressor.score(X_train, Y_train))
print('Test Coefficient of R^2 : %.3f'%bag_regressor.score(X_test, Y_test))

In [ ]:

%%time

n_samples = boston.data.shape[0]
n_features = boston.data.shape[1]

params = {'base_estimator': [None, LinearRegression(), KNeighborsRegressor()],
          'n_estimators': [20,50,100],
          'max_samples': [0.5,1.0],
          'max_features': [0.5,1.0],
          'bootstrap': [True, False],
          'bootstrap_features': [True, False]}

bagging_regressor_grid = GridSearchCV(BaggingRegressor(random_state=1, n_jobs=-1), param_grid =params, cv=3, n_jobs=-1, verbose=1)
bagging_regressor_grid.fit(X_train, Y_train)

print('Train R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_train, Y_train))
print('Test R^2 Score : %.3f'%bagging_regressor_grid.best_estimator_.score(X_test, Y_test))
print('Best R^2 Score Through Grid Search : %.3f'%bagging_regressor_grid.best_score_)
print('Best Parameters : ',bagging_regressor_grid.best_params_)

# "Bagging aur Bagging Ensemble almost same hi use hote hain. Bagging ek ensemble learning technique hai jisme multiple same-type models ko bootstrap samples par train karke unki predictions ko majority voting ya averaging se combine kiya jata hai."

# Bagging Classifier

"Bagging Classifier ek machine learning algorithm hai jo ek classifier ki jagah bahut saare same classifiers ko alag-alag random data par train karta hai aur un sabki majority voting se final class predict karta hai."

# Example

Maan lo tumhare paas 5 Decision Trees hain.

Tree 1 → Cat

Tree 2 → Dog

Tree 3 → Dog

Tree 4 → Dog

Tree 5 → Cat

Majority vote:

Dog = 3 votes

Cat = 2 votes

✅ Final Prediction = Dog

# Bagging Regressor

Bagging Regressor ek machine learning algorithm hai jo regression problems (continuous values jaise house price, salary, temperature) ke liye bahut saare same regressors ko alag-alag bootstrap samples par train karta hai aur un sabki predictions ka average lekar final prediction deta hai."

# Example

House price predict karni hai.

5 models predict karte hain:

Model 1 → ₹48 Lakh

Model 2 → ₹50 Lakh

Model 3 → ₹49 Lakh

Model 4 → ₹51 Lakh

Model 5 → ₹52 Lakh

Final prediction:

(48 + 50 + 49 + 51 + 52) / 5
= ₹50 Lakh

Yaani average prediction final answer ban jaati hai.

# Bagging vs Voting

```
| **Bagging**                                                                                            | **Voting**                                                                              |
| ------------------------------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------- |
| Ek hi dataset se **alag-alag bootstrap samples** (random sampling with replacement) banaye jaate hain. | Sab models **same original dataset** par train hote hain.                               |
| Har model ko **different bootstrap sample** milta hai.                                                 | Har model ko **same data** milta hai.                                                   |
| Aksar **same type ke models** hote hain (jaise 100 Decision Trees).                                    | Aksar **different type ke models** hote hain (Decision Tree, SVM, Logistic Regression). |
```

 # Example

 # Bagging

 Original Data:

1000 rows

Bootstrap Sampling:

Tree 1 → Random 1000 rows (duplicates ho sakte hain)

Tree 2 → Random 1000 rows

Tree 3 → Random 1000 rows

Tree 4 → Random 1000 rows

👉 Har tree different data par train hota hai.

# Goal: Variance kam karna

# Voting

Original Data:

1000 rows

Training:

Decision Tree → Same 1000 rows

SVM           → Same 1000 rows

Logistic Reg. → Same 1000 rows

KNN           → Same 1000 rows

👉 Sab models same data par train hote hain, bas algorithm alag hote hain.

# Goal: Different models ki strengths ko combine karna.