In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df = pd.read_csv('diabetes.csv')

In [36]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [37]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [38]:
df.shape

(768, 9)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [40]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

# Numerical Analysis

We analysis Glucose

In [41]:
df['Glucose'].describe()

count    768.000000
mean     120.894531
std       31.972618
min        0.000000
25%       99.000000
50%      117.000000
75%      140.250000
max      199.000000
Name: Glucose, dtype: float64

In [42]:
df['Glucose'].mean()

np.float64(120.89453125)

In [43]:
df['Glucose'].median()

117.0

In [44]:
df['Glucose'].std()

31.97261819513622

# Categorical Anaylsis

We anyalsis Age

In [45]:
df['Age'].value_counts()

Age
22    72
21    63
25    48
24    46
23    38
28    35
26    33
27    32
29    29
31    24
41    22
30    21
37    19
42    18
33    17
36    16
38    16
32    16
45    15
34    14
46    13
40    13
43    13
39    12
35    10
44     8
50     8
51     8
52     8
58     7
54     6
47     6
49     5
60     5
53     5
57     5
48     5
63     4
66     4
55     4
62     4
59     3
56     3
65     3
67     3
61     2
69     2
72     1
81     1
64     1
70     1
68     1
Name: count, dtype: int64

In [46]:
df.sort_index(axis=0,ascending=False)

# means it rearranges the rows based on their row numbers (index) in reverse order (bottom to top).

# Simple breakdown:

# sort_index() → sort using row numbers

# axis=0 → rows

# ascending=False → descending order (reverse)

# axis = 0 (Row)
# axis = 1 (Column)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
767,1,93,70,31,0,30.4,0.315,23,0
766,1,126,60,0,0,30.1,0.349,47,1
765,5,121,72,23,112,26.2,0.245,30,0
764,2,122,70,27,0,36.8,0.340,27,0
763,10,101,76,48,180,32.9,0.171,63,0
...,...,...,...,...,...,...,...,...,...
4,0,137,40,35,168,43.1,2.288,33,1
3,1,89,66,23,94,28.1,0.167,21,0
2,8,183,64,0,0,23.3,0.672,32,1
1,1,85,66,29,0,26.6,0.351,31,0
0,6,148,72,35,0,33.6,0.627,50,1

In [47]:
df.loc[0,0] = 654

In [48]:
df.drop(0,axis=1)

# means it deletes the column named 0 from the DataFrame.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [49]:
df.reset_index()

# resets the row numbers (index) to normal 0, 1, 2, 3… but keeps the old index as a new column.

,index,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,0
0,0,6,148,72,35,0,33.6,0.627,50,1,654.0
1,1,1,85,66,29,0,26.6,0.351,31,0,NaN
2,2,8,183,64,0,0,23.3,0.672,32,1,NaN
3,3,1,89,66,23,94,28.1,0.167,21,0,NaN
4,4,0,137,40,35,168,43.1,2.288,33,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...
763,763,10,101,76,48,180,32.9,0.171,63,0,NaN
764,764,2,122,70,27,0,36.8,0.340,27,0,NaN
765,765,5,121,72,23,112,26.2,0.245,30,0,NaN
766,766,1,126,60,0,0,30.1,0.349,47,1,NaN
767,767,1,93,70,31,0,30.4,0.315,23,0,NaN

In [50]:
df.reset_index(drop=True,inplace = True)
# It just fixes the row numbers back to normal (0,1,2,3…) and removes the old messy numbers permanently.

In [51]:
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,0
0,6,148,72,35,0,33.6,0.627,50,1,654.0
1,1,85,66,29,0,26.6,0.351,31,0,NaN
2,8,183,64,0,0,23.3,0.672,32,1,NaN

In [52]:
df.isnull() # checks your data and shows where values are missing (empty cells).

# Simple idea:
# If a value is missing → True
# If a value is present → False

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,0
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False,True
764,False,False,False,False,False,False,False,False,False,True
765,False,False,False,False,False,False,False,False,False,True
766,False,False,False,False,False,False,False,False,False,True
767,False,False,False,False,False,False,False,False,False,True

# Dataframe

DataFrame is like a table of data (rows and columns) in Python, similar to an Excel sheet.

In [53]:
data = {
    "Name": ["A", "B"],
    "Age": [20, 22],
    "Marks": [85, 90]
}

df = pd.DataFrame(data)
print(df)

  Name  Age  Marks
0    A   20     85
1    B   22     90

In [54]:
df.dropna()

  Name  Age  Marks
0    A   20     85
1    B   22     90

In [55]:
df.drop_duplicates(subset='Name')

# Remove duplicate rows based only on the "name" column.

  Name  Age  Marks
0    A   20     85
1    B   22     90

In [56]:
df['Name'].value_counts(dropna=False)

Name
A    1
B    1
Name: count, dtype: int64

In [57]:
df.fillna('Name') # s used to fill missing (NaN) values in a dataset.

  Name  Age  Marks
0    A   20     85
1    B   22     90

# What is the df['column'] and something ?

👉 If data is inside dataframe → use df['column']

👉 If it is separate value → use normal variable

# Groupby

Group similar values together and then perform some calculation on them

If you have student marks data and you want:

Average marks per class

Total salary per department

Total sales per month

# We use Groupby()

In [59]:
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000, 45000, 70000]
}
df = pd.DataFrame(data)
print(df)

  Name Department  Salary
0    A         IT   50000
1    B         HR   40000
2    C         IT   60000
3    D         HR   45000
4    E         IT   70000

# Total Salary Per Department

In [60]:
df.groupby('Department')['Salary'].sum()

Department
HR     85000
IT    180000
Name: Salary, dtype: int64

# Average Salary Per Department

In [61]:
df.groupby('Department')['Salary'].mean()

Department
HR    42500.0
IT    60000.0
Name: Salary, dtype: float64

# For function

.sum()
.mean()
.count()
.max()
.min()

# Lambda in GroupBy

Because sometime we built

.sum()

.mean()

.max()

In [ ]:
# Salary Range Per Department

# Range = max-min

df.groupby("Department")["Salary"].agg(lambda x: x.max() - x.min())

# groupby.filter

In [62]:
df.groupby("Department").filter(lambda x: x["Salary"].mean() > 50000)

  Name Department  Salary
0    A         IT   50000
2    C         IT   60000
4    E         IT   70000

# Sort_index

In [64]:
df.groupby("Department")["Salary"].sum().sort_index(ascending=True)

# If ascending=False → reverse order.

Department
HR     85000
IT    180000
Name: Salary, dtype: int64

In [66]:
df.groupby("Department")["Salary"].sum().sort_values(ascending=False)

# If ascending=True → smallest revenue first.

Department
IT    180000
HR     85000
Name: Salary, dtype: int64

 sort_index() → sorts by group names (index)

sort_values() → sorts by aggregated values

ascending=True → small → large

ascending=False → large → small

# Indexing array

# 1️⃣ Indexing starts at 0

First element → index 0

Second element → index 1

Third element → index 2

# Example

arr = [10, 20, 30, 40]

arr[0] → 10

arr[2] → 30

# 2️⃣ Slicing: arr[start:end]

start → inclusive (included)

end → exclusive (stop before this index)

# Exmaple

arr[:3]   # first three elements → [10, 20, 30]

arr[1:4]  # index 1,2,3 → [20, 30, 40]

# 3️⃣ Negative index & steps

Negative index counts from end:

-1 → last element

-2 → second last element

Step / skip elements: arr[start:end:step]

# Exmaple

arr[-2:]   # last 2 elements → [30, 40]

arr[::2]   # every 2nd element → [10, 30]

# Bonus point remember

“Start included, End excluded” → always stops before end index.
If start > end → empty array

# Shape

Quick Tips

len(df) → gives number of rows only

df.shape[0] → number of rows

df.shape[1] → number of columns

# When do we use df[ df[condition] ]

Filtering rows based on column values

Combining multiple conditions

Cleaning data (e.g., remove outliers)

Selecting specific subset for analysis or ML

# drop_duplicate

Removes duplicate rows from a DataFrame

Keeps only the first occurrence (by default)

Can remove duplicates based on all columns or specific columns

# Subset

Which column(s) to check for duplicates. Default is None → check all columns

# keep

Which duplicate to keep: 'first', 'last', or False (drop all duplicates)

# inplace

If True → changes the original DataFrame; if False → returns new DataFrame

In [ ]:
# Syntax

df.drop_duplicates(subset=None, keep='first', inplace=False)